### ISSUE TITLE
License not specified for coveraggregator

### ISSUE THREAD

**Issue by zmedico** [chouquette/coveraggregator#1]
Would you please specify a license for coveraggregator? I would like to package coveraggregator for Gentoo Linux, but I'll need a license in order to do that. It would be helpful if the repository included a LICENSE or COPYING file. Thank you!

**Comment by chouquette** [comment]
Oh my, I forgot about this project :)

I just pushed a license file, please do whatever you feel like with this code! Thanks for packaging this, I hope it will help someone :)
